// <Auto-Generated></Auto-Generated>
using System.Runtime.CompilerServices;
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

namespace Juxtapose;

/// <summary>
/// <see cref="SynchronizationContext"/> 移除器
/// https://docs.microsoft.com/zh-cn/archive/blogs/benwilli/an-alternative-to-configureawaitfalse-everywhere
/// </summary>
public sealed class SynchronizationContextRemover : INotifyCompletion
{
    /// <summary>
    /// Awaiter
    /// </summary>
    public static SynchronizationContextRemover Awaiter { get; } = new();

    public bool IsCompleted
    {
        get { return SynchronizationContext.Current == null; }
    }

    public SynchronizationContextRemover GetAwaiter()
    {
        return this;
    }

    public void OnCompleted(Action continuation)
    {
        var prevContext = SynchronizationContext.Current;
        if (prevContext is null)
        {
            continuation();
        }
        else
        {
            try
            {
                SynchronizationContext.SetSynchronizationContext(null);
                continuation();
            }
            finally
            {
                SynchronizationContext.SetSynchronizationContext(prevContext);
            }
        }
    }

    public void GetResult()
    {
    }
}