namespace Juxtapose.SourceGenerator
{
    public static class Constants
    {
        #region Public 字段

        public const string JuxtaposeGenerateCodeHeader = @"// <Auto-Generated/>
// Generated by Juxtapose.SourceGenerator

#nullable enable

using global::System;
using global::System.Threading;
using global::System.Threading.Tasks;

using global::Juxtapose;
using global::Juxtapose.Messages;
using global::Juxtapose.Messages.ParameterPacks;
using global::Juxtapose.Messages.ParameterPacks.Generated;";

        #endregion Public 字段
    }
}