// <Auto-Generated></Auto-Generated>

using Microsoft.CodeAnalysis;

namespace Juxtapose.SourceGenerator
{
    internal static class DiagnosticDescriptorCategories
    {
        public const string ExecutorGenerate = "Juxtapose.SourceGenerator.ExecutorGenerate";
    }

    internal static class DiagnosticDescriptors
    {
        public static DiagnosticDescriptor ExecutorGenerateCanNotFoundGeneratedRealObjectInvoker { get; } = new("JSG0001", "未找到生成类型。", "未找到类型 {0} 对应继承类型 {1} 的 RealObjectInvoker 生成源码。", DiagnosticDescriptorCategories.ExecutorGenerate, DiagnosticSeverity.Error, true);
    }
}
